#ifndef OCALLS_READER_H
#define OCALLS_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct __ocall_wrapper_print_int_table *__ocall_wrapper_print_int_table_t;
typedef struct __ocall_wrapper_print_int_table *__ocall_wrapper_print_int_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_print_int_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_print_int_mutable_vec_t;
typedef const struct __ocall_wrapper_print_string_table *__ocall_wrapper_print_string_table_t;
typedef struct __ocall_wrapper_print_string_table *__ocall_wrapper_print_string_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_print_string_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_print_string_mutable_vec_t;
#ifndef __ocall_wrapper_print_int_identifier
#define __ocall_wrapper_print_int_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_print_int_type_hash ((flatbuffers_thash_t)0x8baed42e)
#define __ocall_wrapper_print_int_type_identifier "\x2e\xd4\xae\x8b"
#ifndef __ocall_wrapper_print_string_identifier
#define __ocall_wrapper_print_string_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_print_string_type_hash ((flatbuffers_thash_t)0x5f69fd28)
#define __ocall_wrapper_print_string_type_identifier "\x28\xfd\x69\x5f"



struct __ocall_wrapper_print_int_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_print_int_vec_len(__ocall_wrapper_print_int_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_print_int_table_t __ocall_wrapper_print_int_vec_at(__ocall_wrapper_print_int_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_print_int_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_print_int)

__flatbuffers_define_scalar_field(0, __ocall_wrapper_print_int, msg, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(1, __ocall_wrapper_print_int, __return_value, flatbuffers_int64, int64_t, INT64_C(0))

struct __ocall_wrapper_print_string_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_print_string_vec_len(__ocall_wrapper_print_string_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_print_string_table_t __ocall_wrapper_print_string_vec_at(__ocall_wrapper_print_string_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_print_string_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_print_string)

__flatbuffers_define_vector_field(0, __ocall_wrapper_print_string, msg, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_scalar_field(1, __ocall_wrapper_print_string, __return_value, flatbuffers_int64, int64_t, INT64_C(0))


#include "flatcc/flatcc_epilogue.h"
#endif /* OCALLS_READER_H */
