#ifndef OCALLS_VERIFIER_H
#define OCALLS_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef OCALLS_READER_H
#include "ocalls_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"


#include "flatcc/flatcc_epilogue.h"
#endif /* OCALLS_VERIFIER_H */
